#!/bin/bash
# Installation et configuration
sudo apt-get install thunderbird zim git git-lfs rxvt-unicode vlc deja-dup freetuxtv grisbi filezilla keeppassxc krita zsh kanatest calibre redshift chromium liferea gimp inkscape vim mcomix

## Couleur et avatar
ln -sf `pwd`/conf/face ~/.face
ln -sf `pwd`/conf/Xresources ~/.Xresources
ln -sf `pwd`/conf/xresources ~/.xresources
ln -sf `pwd`/conf/fonts ~/.fonts

ln -sf `pwd`/conf/.gtk-bookmarks ~/.gtk-bookmarks

## Mes scripts
ln -sf `pwd`/scripts ~/.scripts

## Git
ln -sf `pwd`/conf/gitconfig ~/.gitconfig

## Npm
ln -sf `pwd`/conf/npmrc ~/.npmrc

## Zsh

### Installation de Oh my zsh
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

### Plugins - Installation
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-autosuggestions.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
sudo apt-get install autojump

### Custom
ln -sf `pwd`/conf/zsh/zshrc ~/.zshrc
