# Path to your oh-my-zsh installation.
export ZSH="/home/bastienrc/.oh-my-zsh"

# Set name of the theme to load
ZSH_THEME="gallifrey"

# Default User cache le "user@hostname" en local
DEFAULT_USER="Bastienrc" # 

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM=$HOME/.zsh_custom

# Plugins - Load
plugins=(git npm autojump zsh-autosuggestions zsh-syntax-highlighting)

# NVM: Node Version Manager
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

source $ZSH/oh-my-zsh.sh