#
# Oh My Zsh Configuration
#
export ZSH=$HOME/.oh-my-zsh

# Theme ( ~/.oh-my-zsh/themes/)
# ZSH_THEME="agnoster"
ZSH_THEME="gallifrey"
DEFAULT_USER="bastienrc" # Cache le "user@hostname" en local

# Mes customisations, tel que mes Alias
ZSH_CUSTOM=$HOME/.zsh_custom

# Mise à jour automatique sans invite
DISABLE_UPDATE_PROMPT=true

# Plugins
# Ajouter à bon escient, trop de plugins ralenti le démarrage du shell.
plugins=(
  git
  git-flow
  npm
)

source $ZSH/oh-my-zsh.sh
