#!/bin/sh
# Droit d'access : sudo chmod 755 php

docker run \
    --network=host \
    --rm \
    --name php\
    -e HOME="$HOME" \
    -u $(id -u):$(id -g) \
    -v "$HOME":"$HOME" \
    -w "$PWD" \
    php:cli-alpine \
    php "$@"

exit $?