#!/bin/zsh
# Script exécuter au démarrage de Xfce4
#

# Démarage de mes containers
# Laradock
#cd /data/Lab/laradock && docker-compose up -d nginx mysql phpmyadmin

# Portainer
# cd /data/Lab/docker && docker-compose up -d && cd /data/Lab


# Conky, lancement en daemon après une pause d'une seconde.
cd /data/Lab/dotfiles/conf/conky && conky -d -p 5 -c conkyrc
